import { Router } from 'express';
import authRoutes from './authRoutes.js';
import serviceRoutes from './serviceRoutes.js';
import feedRoutes from './feedRoutes.js';
import searchRoutes from './searchRoutes.js';
import adminRoutes from './adminRoutes.js';
import telemetryRoutes from './telemetryRoutes.js';
import zoneRoutes from './zoneRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import inventoryRoutes from './inventoryRoutes.js';
import rentalRoutes from './rentalRoutes.js';
import complianceRoutes from './complianceRoutes.js';
import marketplaceRoutes from './marketplaceRoutes.js';
import materialsRoutes from './materialsRoutes.js';
import campaignRoutes from './campaignRoutes.js';
import communicationsRoutes from './communicationsRoutes.js';
import analyticsPipelineRoutes from './analyticsPipelineRoutes.js';
import panelRoutes from './panelRoutes.js';
import businessFrontRoutes from './businessFrontRoutes.js';
import blogRoutes from './blogRoutes.js';
import adminBlogRoutes from './adminBlogRoutes.js';
import affiliateRoutes from './affiliateRoutes.js';
import consentRoutes from './consentRoutes.js';
import financeRoutes from './financeRoutes.js';
import accountSupportRoutes from './accountSupportRoutes.js';

const v1Router = Router();

v1Router.use('/auth', authRoutes);
v1Router.use('/services', serviceRoutes);
v1Router.use('/feed', feedRoutes);
v1Router.use('/search', searchRoutes);
v1Router.use('/admin', adminRoutes);
v1Router.use('/telemetry', telemetryRoutes);
v1Router.use('/zones', zoneRoutes);
v1Router.use('/bookings', bookingRoutes);
v1Router.use('/inventory', inventoryRoutes);
v1Router.use('/rentals', rentalRoutes);
v1Router.use('/compliance', complianceRoutes);
v1Router.use('/marketplace', marketplaceRoutes);
v1Router.use('/materials', materialsRoutes);
v1Router.use('/campaigns', campaignRoutes);
v1Router.use('/communications', communicationsRoutes);
v1Router.use('/analytics', analyticsPipelineRoutes);
v1Router.use('/panel', panelRoutes);
v1Router.use('/business-fronts', businessFrontRoutes);
v1Router.use('/blog', blogRoutes);
v1Router.use('/admin/blog', adminBlogRoutes);
v1Router.use('/affiliate', affiliateRoutes);
v1Router.use('/consent', consentRoutes);
v1Router.use('/finance', financeRoutes);
v1Router.use('/account-support', accountSupportRoutes);

const router = Router();

router.use('/v1', v1Router);
router.use('/', v1Router);

export { v1Router };
export default router;
