import { Router } from 'express';
import authRoutes from './authRoutes.js';
import serviceRoutes from './serviceRoutes.js';
import feedRoutes from './feedRoutes.js';
import searchRoutes from './searchRoutes.js';
import adminLiveFeedAuditRoutes from './adminLiveFeedAuditRoutes.js';
import adminRoutes from './adminRoutes.js';
import adminRentalRoutes from './adminRentalRoutes.js';
import adminServiceManagementRoutes from './adminServiceManagementRoutes.js';
import telemetryRoutes from './telemetryRoutes.js';
import zoneRoutes from './zoneRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import inventoryRoutes from './inventoryRoutes.js';
import rentalRoutes from './rentalRoutes.js';
import complianceRoutes from './complianceRoutes.js';
import marketplaceRoutes from './marketplaceRoutes.js';
import materialsRoutes from './materialsRoutes.js';
import campaignRoutes from './campaignRoutes.js';
import communicationsRoutes from './communicationsRoutes.js';
import analyticsPipelineRoutes from './analyticsPipelineRoutes.js';
import panelRoutes from './panelRoutes.js';
import businessFrontRoutes from './businessFrontRoutes.js';
import blogRoutes from './blogRoutes.js';
import adminBlogRoutes from './adminBlogRoutes.js';
import adminBookingRoutes from './adminBookingRoutes.js';
import adminHomeBuilderRoutes from './adminHomeBuilderRoutes.js';
import affiliateRoutes from './affiliateRoutes.js';
import consentRoutes from './consentRoutes.js';
import financeRoutes from './financeRoutes.js';
import walletRoutes from './walletRoutes.js';
import customerServiceManagementRoutes from './customerServiceManagementRoutes.js';
import accountSupportRoutes from './accountSupportRoutes.js';
import { adminWalletRouter, walletRouter } from './walletRoutes.js';
import adminWalletRoutes from './adminWalletRoutes.js';
import walletRoutes from './walletRoutes.js';
import adminEnterpriseRoutes from './adminEnterpriseRoutes.js';
import adminMarketplaceRoutes from './adminMarketplaceRoutes.js';
import legalRoutes from './legalRoutes.js';
import userSettingsRoutes from './userSettingsRoutes.js';
import serviceOrderRoutes from './serviceOrderRoutes.js';
import customerControlRoutes from './customerControlRoutes.js';
import accountRoutes from './accountRoutes.js';
import servicemanFinanceRoutes from './servicemanFinanceRoutes.js';
import servicemanTaxRoutes from './servicemanTaxRoutes.js';
import servicemanRoutes from './servicemanRoutes.js';
import servicemanSettingsRoutes from './servicemanSettingsRoutes.js';
import providerCalendarRoutes from './providerCalendarRoutes.js';
import servicemanBookingRoutes from './servicemanBookingRoutes.js';
import providerEscrowRoutes from './providerEscrowRoutes.js';
import servicemanEscrowRoutes from './servicemanEscrowRoutes.js';
import servicemanControlRoutes from './servicemanControlRoutes.js';
import fixnadoAdsRoutes from './fixnadoAdsRoutes.js';
import providerRoutes from './providerRoutes.js';

const v1Router = Router();

v1Router.use('/auth', authRoutes);
v1Router.use('/services', serviceRoutes);
v1Router.use('/feed', feedRoutes);
v1Router.use('/search', searchRoutes);
v1Router.use('/admin/bookings', adminBookingRoutes);
v1Router.use('/admin/rentals', adminRentalRoutes);
v1Router.use('/admin/services', adminServiceManagementRoutes);
v1Router.use('/admin/live-feed', adminLiveFeedAuditRoutes);
v1Router.use('/admin', adminRoutes);
v1Router.use('/admin/enterprise', adminEnterpriseRoutes);
v1Router.use('/telemetry', telemetryRoutes);
v1Router.use('/zones', zoneRoutes);
v1Router.use('/bookings', bookingRoutes);
v1Router.use('/inventory', inventoryRoutes);
v1Router.use('/rentals', rentalRoutes);
v1Router.use('/compliance', complianceRoutes);
v1Router.use('/marketplace', marketplaceRoutes);
v1Router.use('/materials', materialsRoutes);
v1Router.use('/admin/marketplace', adminMarketplaceRoutes);
v1Router.use('/campaigns', campaignRoutes);
v1Router.use('/communications', communicationsRoutes);
v1Router.use('/analytics', analyticsPipelineRoutes);
v1Router.use('/panel', panelRoutes);
v1Router.use('/business-fronts', businessFrontRoutes);
v1Router.use('/blog', blogRoutes);
v1Router.use('/admin/blog', adminBlogRoutes);
v1Router.use('/admin/home-builder', adminHomeBuilderRoutes);
v1Router.use('/affiliate', affiliateRoutes);
v1Router.use('/consent', consentRoutes);
v1Router.use('/finance', financeRoutes);
v1Router.use('/customer/services', customerServiceManagementRoutes);
v1Router.use('/account-support', accountSupportRoutes);
v1Router.use('/admin/wallets', adminWalletRouter);
v1Router.use('/admin/wallets', adminWalletRoutes);
v1Router.use('/legal', legalRoutes);
v1Router.use('/settings', userSettingsRoutes);
v1Router.use('/wallet', walletRouter);
v1Router.use('/service-orders', serviceOrderRoutes);
v1Router.use('/customer-control', customerControlRoutes);
v1Router.use('/serviceman-control', servicemanControlRoutes);
v1Router.use('/account', accountRoutes);
v1Router.use('/servicemen/finance', servicemanFinanceRoutes);
v1Router.use('/servicemen/tax', servicemanTaxRoutes);
v1Router.use('/servicemen', servicemanRoutes);
v1Router.use('/serviceman', servicemanRoutes);
v1Router.use('/servicemen/settings', servicemanSettingsRoutes);
v1Router.use('/providers', providerCalendarRoutes);
v1Router.use('/serviceman/bookings', servicemanBookingRoutes);
v1Router.use('/provider/escrows', providerEscrowRoutes);
v1Router.use('/serviceman', servicemanEscrowRoutes);
v1Router.use('/fixnado/ads', fixnadoAdsRoutes);
v1Router.use('/provider', providerRoutes);

const router = Router();

router.use('/v1', v1Router);
router.use('/', v1Router);

export { v1Router };
export default router;
