export const Permissions = Object.freeze({
  ADMIN_DASHBOARD: 'admin:dashboard',
  ADMIN_DASHBOARD_WRITE: 'admin:dashboard:configure',
  ADMIN_FEATURE_READ: 'admin:feature-toggle:read',
  ADMIN_FEATURE_WRITE: 'admin:feature-toggle:write',
  ADMIN_PLATFORM_READ: 'admin:platform-settings:read',
  ADMIN_PLATFORM_WRITE: 'admin:platform-settings:write',
  ADMIN_BOOKINGS_READ: 'admin:bookings:read',
  ADMIN_BOOKINGS_WRITE: 'admin:bookings:write',
  ADMIN_CUSTOM_JOBS_READ: 'admin:custom-jobs:read',
  ADMIN_CUSTOM_JOBS_WRITE: 'admin:custom-jobs:write',
  ADMIN_RBAC_READ: 'admin:rbac:read',
  ADMIN_RBAC_WRITE: 'admin:rbac:write',
  ADMIN_PROFILE_READ: 'admin:profile:read',
  ADMIN_PROFILE_WRITE: 'admin:profile:write',
  ADMIN_SETTINGS_READ: 'admin:preferences:read',
  ADMIN_SETTINGS_WRITE: 'admin:preferences:write',
  ADMIN_AUTOMATION_READ: 'admin:automation:read',
  ADMIN_AUTOMATION_WRITE: 'admin:automation:write',
  ADMIN_APPEARANCE_READ: 'admin:appearance:read',
  ADMIN_APPEARANCE_WRITE: 'admin:appearance:write',
  ADMIN_LIVE_FEED_AUDIT_READ: 'admin:live-feed:audit:read',
  ADMIN_LIVE_FEED_AUDIT_WRITE: 'admin:live-feed:audit:write',
  ADMIN_AFFILIATE_READ: 'admin:affiliate:read',
  ADMIN_AFFILIATE_WRITE: 'admin:affiliate:write',
  ADMIN_ESCROW_READ: 'admin:escrow:read',
  ADMIN_ESCROW_WRITE: 'admin:escrow:write',
  PROVIDER_ESCROW_READ: 'provider:escrow:read',
  PROVIDER_ESCROW_WRITE: 'provider:escrow:write',
  ADMIN_PROVIDER_READ: 'admin:provider:read',
  ADMIN_PROVIDER_WRITE: 'admin:provider:write',
  ADMIN_PROVIDER_ARCHIVE: 'admin:provider:archive',
  ADMIN_COMMAND_METRICS_READ: 'admin:command-metrics:read',
  ADMIN_COMMAND_METRICS_WRITE: 'admin:command-metrics:write',
  SERVICEMAN_METRICS_READ: 'serviceman:metrics:read',
  SERVICEMAN_METRICS_WRITE: 'serviceman:metrics:write',
  ADMIN_OPERATIONS_QUEUE_READ: 'admin:operations-queue:read',
  ADMIN_OPERATIONS_QUEUE_WRITE: 'admin:operations-queue:write',
  ADMIN_USER_READ: 'admin:user:read',
  ADMIN_USER_WRITE: 'admin:user:write',
  ADMIN_USER_INVITE: 'admin:user:invite',
  ADMIN_ENTERPRISE_READ: 'admin:enterprise:read',
  ADMIN_ENTERPRISE_WRITE: 'admin:enterprise:write',
  ADMIN_INBOX_READ: 'admin:inbox:read',
  ADMIN_INBOX_WRITE: 'admin:inbox:write',
  ADMIN_RENTAL_READ: 'admin:rentals:read',
  ADMIN_RENTAL_WRITE: 'admin:rentals:write',
  ADMIN_PURCHASE_READ: 'admin:purchase:read',
  ADMIN_PURCHASE_WRITE: 'admin:purchase:write',
  ADMIN_PURCHASE_BUDGET: 'admin:purchase:budget',
  ADMIN_SERVICES_READ: 'admin:services:read',
  ADMIN_SERVICES_WRITE: 'admin:services:write',
  ADMIN_HOME_BUILDER: 'admin:home-builder:manage',
  ADMIN_LEGAL_READ: 'admin:legal:read',
  ADMIN_LEGAL_WRITE: 'admin:legal:write',
  ADMIN_WEBSITE_READ: 'admin:website:read',
  ADMIN_WEBSITE_WRITE: 'admin:website:write',
  ADMIN_AUDIT_READ: 'admin:audit:read',
  ADMIN_AUDIT_WRITE: 'admin:audit:write',
  ADMIN_COMPLIANCE_READ: 'admin:compliance:read',
  ADMIN_COMPLIANCE_WRITE: 'admin:compliance:write',
  ADMIN_TAXONOMY_READ: 'admin:taxonomy:read',
  ADMIN_TAXONOMY_WRITE: 'admin:taxonomy:write',
  ADMIN_SECURITY_POSTURE_READ: 'admin:security:posture:read',
  ADMIN_SECURITY_POSTURE_WRITE: 'admin:security:posture:write',
  AFFILIATE_DASHBOARD: 'affiliate:dashboard:view',
  AFFILIATE_REFERRALS: 'affiliate:referrals:view',
  ANALYTICS_OVERVIEW: 'analytics:overview:view',
  ANALYTICS_EXPORT: 'analytics:export:run',
  ACCOUNT_SETTINGS_MANAGE: 'account:settings:manage',
  SERVICEMAN_PROFILE_MANAGE: 'serviceman:profile:manage',
  CAMPAIGN_MANAGE: 'campaign:manage',
  CAMPAIGN_REVIEW: 'campaign:review',
  COMPLIANCE_PORTAL: 'compliance:portal:access',
  COMPLIANCE_EXPORT: 'compliance:export:execute',
  COMPLIANCE_WAREHOUSE_VIEW: 'compliance:data-warehouse:view',
  COMPLIANCE_WAREHOUSE_EXPORT: 'compliance:data-warehouse:export',
  DISPUTE_MANAGE: 'finance:dispute:manage',
  DISPUTE_VIEW: 'finance:dispute:view',
  FEED_VIEW: 'feed:live:view',
  FEED_POST: 'feed:live:post',
  FEED_BID: 'feed:live:bid',
  FEED_MESSAGE: 'feed:live:message',
  FINANCE_OVERVIEW: 'finance:overview:view',
  FINANCE_PAYOUT_MANAGE: 'finance:payout:manage',
  FINANCE_PAYOUT_VIEW: 'finance:payout:view',
  FINANCE_WALLET_VIEW: 'finance:wallet:view',
  FINANCE_WALLET_MANAGE: 'finance:wallet:manage',
  INTEGRATION_CONSOLE: 'integration:console:manage',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  MATERIALS_VIEW: 'materials:showcase:view',
  SERVICEMAN_IDENTITY_MANAGE: 'servicemen:identity:manage',
  MESSAGING_READ: 'messaging:threads:read',
  MESSAGING_RESPOND: 'messaging:threads:respond',
  MESSAGING_ESCALATE: 'messaging:threads:escalate',
  PANEL_PROVIDER: 'panel:provider:view',
  PANEL_PROVIDER_UPGRADE: 'panel:provider:upgrade',
  PANEL_PROVIDER_TOOLS: 'panel:provider:tools:manage',
  PANEL_ENTERPRISE: 'panel:enterprise:view',
  PANEL_STOREFRONT: 'panel:storefront:view',
  PANEL_PROVIDER_SERVICEMAN_FINANCE_VIEW: 'panel:provider:serviceman-finance:view',
  PANEL_PROVIDER_SERVICEMAN_FINANCE_MANAGE: 'panel:provider:serviceman-finance:manage',
  PAYMENTS_CAPTURE: 'payments:capture',
  PAYMENTS_REFUND: 'payments:refund',
  PAYMENTS_RELEASE: 'payments:release',
  WALLET_VIEW: 'wallet:accounts:view',
  WALLET_MANAGE: 'wallet:accounts:manage',
  WALLET_TRANSACT: 'wallet:transactions:create',
  WALLET_METHOD_MANAGE: 'wallet:payment-methods:manage',
  PROVIDER_ONBOARD: 'provider:onboard:manage',
  PROVIDER_CALENDAR_VIEW: 'provider:calendar:view',
  PROVIDER_CALENDAR_MANAGE: 'provider:calendar:manage',
  REPORTING_DOWNLOAD: 'reporting:download',
  SCHEDULE_MANAGE: 'schedule:manage',
  SERVICE_ORDERS_VIEW: 'service-orders:view',
  SERVICE_ORDERS_MANAGE: 'service-orders:manage',
  SERVICEMAN_BOOKINGS_VIEW: 'serviceman:bookings:view',
  SERVICEMAN_BOOKINGS_MANAGE: 'serviceman:bookings:manage',
  SERVICES_MANAGE: 'services:manage',
  SERVICES_BOOK: 'services:book',
  SERVICEMAN_ESCROW_VIEW: 'serviceman:escrow:view',
  SERVICEMAN_ESCROW_MANAGE: 'serviceman:escrow:manage',
  SUPPORT_TICKETS: 'support:tickets:manage',
  SERVICEMAN_WEBSITE_READ: 'serviceman:website:read',
  SERVICEMAN_WEBSITE_WRITE: 'serviceman:website:write',
  CUSTOMER_CONTROL_MANAGE: 'customer:control:manage',
  SERVICEMAN_CONTROL_MANAGE: 'serviceman:control:manage',
  USER_DIRECTORY: 'user:directory:view',
  ZONES_READ: 'zones:read',
  ZONES_MANAGE: 'zones:manage',
  ZONES_COVERAGE: 'zones:coverage',
  ZONES_MATCH: 'zones:match',
  ZONES_PREVIEW: 'zones:preview'
});

export const CanonicalRoles = Object.freeze({
  GUEST: 'guest',
  USER: 'user',
  SERVICEMAN: 'serviceman',
  PROVIDER: 'provider',
  ENTERPRISE: 'enterprise',
  PROVIDER_ADMIN: 'provider_admin',
  OPERATIONS: 'operations',
  ADMIN: 'admin'
});

const ALIAS_ENTRIES = [
  ['guest', CanonicalRoles.GUEST],
  ['anonymous', CanonicalRoles.GUEST],
  ['user', CanonicalRoles.USER],
  ['customer', CanonicalRoles.USER],
  ['servicemen', CanonicalRoles.SERVICEMAN],
  ['serviceman', CanonicalRoles.SERVICEMAN],
  ['technician', CanonicalRoles.SERVICEMAN],
  ['crew', CanonicalRoles.SERVICEMAN],
  ['company', CanonicalRoles.PROVIDER],
  ['provider', CanonicalRoles.PROVIDER],
  ['sme', CanonicalRoles.PROVIDER],
  ['enterprise', CanonicalRoles.ENTERPRISE],
  ['corporate', CanonicalRoles.ENTERPRISE],
  ['provider_admin', CanonicalRoles.PROVIDER_ADMIN],
  ['provider-admin', CanonicalRoles.PROVIDER_ADMIN],
  ['operations_admin', CanonicalRoles.OPERATIONS],
  ['operations', CanonicalRoles.OPERATIONS],
  ['ops', CanonicalRoles.OPERATIONS],
  ['admin', CanonicalRoles.ADMIN],
  ['superadmin', CanonicalRoles.ADMIN],
  ['root', CanonicalRoles.ADMIN]
];

export const ROLE_ALIASES = new Map(ALIAS_ENTRIES);

export function normaliseRole(value) {
  if (typeof value !== 'string') {
    return '';
  }
  return value.trim().toLowerCase();
}

export function toCanonicalRole(value) {
  const normalised = normaliseRole(value);
  if (ROLE_ALIASES.has(normalised)) {
    return ROLE_ALIASES.get(normalised);
  }
  if (Object.values(CanonicalRoles).includes(normalised)) {
    return normalised;
  }
  return null;
}

export default {
  Permissions,
  CanonicalRoles,
  ROLE_ALIASES,
  normaliseRole,
  toCanonicalRole
};
