name: fixnado_mobile
version: 0.1.0+1
description: Flutter companion app for Fixnado service marketplace.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
