name: fixnado_mobile
version: 0.1.0+1
description: Flutter companion app for Fixnado service marketplace.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  logging: ^1.2.0
  collection: ^1.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
